Repository valist-io/valist, pull requests merged in 2021-11, with the labels that each got.

#189 Standardize Meta.json across publish types
  go.mod
  go.sum
  internal/command/publish.go
  internal/core/types/types.go
  internal/registry/npm/npm.go
  internal/registry/npm/storage.go
  internal/registry/npm/types.go
  internal/storage/ipfs/ipfs.go
Labels: bug, enhancement

#217 Fix init command
  cmd/valist/cmds.go
  command/init.go
Labels: bug

#227 [BUG] Add projectType to update command
  command/update.go
  prompt/prompt.go
  prompt/validate.go
Labels: bug

#234 Add GetLatestRelease when Valist installing without tag
  command/install.go
Labels: enhancement

#235 Set pin.valist.io as default backup pinning provider
  core/core.go
  storage/estuary/estuary.go
  storage/pinning/pinning.go
  storage/pinning/pinning_test.go
Labels: enhancement
